site_name: LLM-BOOK
site_url: https://github.com/buffaloboyhu/llm-book
theme:
  name: material
  primary: teal
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default # 日间模式
      primary: teal # 上方的
      accent: amber # 链接等可交互元件的高亮色
      # teal
      toggle:
        icon: material/brightness-7 # 图标
        name: 切换至夜间模式 # 鼠标悬浮提示
    - media: "(prefers-color-scheme: dark)"
      scheme: slate # 夜间模式
      primary: black
      accent: indigo
      # teal
      toggle:
        icon: material/brightness-4
        name: 切换至日间模式
  features:
    - navigation.expand
    - navigation.tabs
    - navigation.sections
    - navigation.indexes
    - content.code.copy
    - content.tabs.link
    - content.code.annotate
    - math
    - diagrams
    - toc.integrate
  language: zh


markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.arithmatex:
        generic: true
  - toc:
      permalink: true
      toc_depth: 3


extra_javascript:
  - styles/javascripts/katex.js
  - https://unpkg.com/katex@0/dist/katex.min.js
  - https://unpkg.com/katex@0/dist/contrib/auto-render.min.js

extra_css:
  - styles/title-colors.css
  - https://unpkg.com/katex@0/dist/katex.min.css

nav:
  - 主页: index.md
  - 大模型基础:
      - 自然语言处理（NLP）:
          - NLP: llm-basic/nlp/nlp.md
      - Transformer模型: llm-basic/transformer/transformer.md
      - MoE(专家混合模型): llm-basic/MoE/basic.md

  - 大模型训练:
      - 训练可视化:
          - Swanlab: llm-train/train-visualization/swanlab.md
      - 预训练模型:
          - BERT: llm-train/pretrained/bert.md
          - GPT: llm-train/pretrained/gpt.md
          - LLama: llm-train/pretrained/llama.md
          - ChatGLM: llm-train/pretrained/chatglm.md
      - 训练框架:
          - HuggingFace:
              - Transformers: llm-train/train-framework/huggingface-Transformers.md
          - ModelScope:
              - swift: llm-train/train-framework/ms-swift.md

      - 分布式训练:
          - 分布式工具:
              - DeepSpeed + Accelerate: llm-train/distributed-train/tools/deepspeed.md
              - Megatron-LM: llm-train/distributed-train/tools/Megatron-LM.md
              - ColossaiAI: llm-train/distributed-train/tools/ColossalAI.md

  - 大模型微调:
      - 微调工具:
          - PEFT: llm-tuning/tools/peft.md
          - LLama-Factory: llm-tuning/tools/llama-factory.md
          - Swift: llm-tuning/tools/swift.md

  - 大模型对齐:
      - RLHF: llm-rl/RLHF.md

  - 大模型优化:
      - 量化: llm-optim/quantization.md
      - 剪枝: llm-optim/prune.md
      - 蒸馏: llm-optim/distill.md

  - 大模型评估:
      - 评估工具:
        - OpenCompass: llm-evaluate/tools/OpenCompass.md
        - EvalScope: llm-evaluate/tools/EvalScope.md

  - 大模型部署:
      - 推理工具:
        - vLLM: llm-deploy/vllm.md
        - TensorRT-LLM: llm-deploy/TensorRT-LLM.md
        - LightLLM: llm-deploy/LightLLM.md
        - LMDeploy: llm-deploy/LMDeploy.md
